/*
Script generated by Aqua Data Studio 18.5.0-16 on 四月-27-2019 07:03:45 下午
Objects: DATABASE
*/
DROP DATABASE "scientific_research"
GO

CREATE DATABASE "scientific_research"
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci
GO

USE scientific_research
GO


/*
Script generated by Aqua Data Studio 18.5.0-16 on 四月-27-2019 06:59:29 下午
Database: scientific_research
Schema: <All Schemas>
Objects: TABLE
*/
DROP TABLE "teacher"
GO
DROP TABLE "pt"
GO
DROP TABLE "project"
GO
DROP TABLE "manager"
GO
DROP TABLE "et"
GO
DROP TABLE "essay"
GO
DROP TABLE "bt"
GO
DROP TABLE "book"
GO

CREATE TABLE "book"  ( 
	"bno"        	varchar(25) NOT NULL,
	"bname"      	varchar(25) NULL,
	"bleader"    	varchar(25) NULL,
	"bgrade"     	smallint(6) NULL,
	"bstatus"    	varchar(25) NULL,
	"bstarttime" 	varchar(25) NULL,
	"bupdatetime"	varchar(25) NULL,
	"bendtime"   	varchar(25) NULL,
	"bts"        	varchar(25) NULL,
	PRIMARY KEY("bno")
)
GO
CREATE TABLE "bt"  ( 
	"bno" 	varchar(25) NULL,
	"tno" 	varchar(25) NULL,
	"btno"	int(11) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY("btno")
)
GO
CREATE TABLE "essay"  ( 
	"eno"        	varchar(25) NOT NULL,
	"ename"      	varchar(25) NULL,
	"eleader"    	varchar(25) NULL,
	"egrade"     	varchar(25) NULL,
	"estatus"    	varchar(25) NULL,
	"estarttime" 	varchar(25) NULL,
	"eupdatetime"	varchar(25) NULL,
	"eendtime"   	varchar(25) NULL,
	"ets"        	varchar(25) NULL,
	PRIMARY KEY("eno")
)
GO
CREATE TABLE "et"  ( 
	"eno" 	varchar(25) NULL,
	"tno" 	varchar(25) NULL,
	"etno"	int(11) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY("etno")
)
GO
CREATE TABLE "manager"  ( 
	"mno"   	varchar(50) NOT NULL,
	"mname" 	varchar(50) NULL,
	"mpass" 	varchar(50) NULL,
	"mtatus"	varchar(4) NULL,
	"mts"   	varchar(50) NULL,
	PRIMARY KEY("mno")
)
GO
CREATE TABLE "project"  ( 
	"pno"        	varchar(25) NOT NULL,
	"pname"      	varchar(50) NULL,
	"pleader"    	varchar(50) NULL,
	"pgrade"     	smallint(6) NULL,
	"pstatus"    	varchar(50) NULL,
	"pstarttime" 	varchar(25) NULL,
	"pupdatetime"	varchar(25) NULL,
	"pendtime"   	varchar(25) NULL,
	"pts"        	varchar(25) NULL,
	PRIMARY KEY("pno")
)
GO
CREATE TABLE "pt"  ( 
	"pno" 	varchar(25) NULL,
	"tno" 	varchar(25) NULL,
	"ptno"	int(11) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY("ptno")
)
GO
CREATE TABLE "teacher"  ( 
	"tno"    	varchar(25) NOT NULL,
	"tname"  	varchar(50) NULL,
	"tsex"   	smallint(6) NULL,
	"ttel"   	varchar(25) NULL,
	"tdept"  	varchar(25) NULL,
	"tduty"  	varchar(25) NULL,
	"tpass"  	varchar(50) NULL,
	"temail" 	varchar(50) NULL,
	"tstatus"	varchar(25) NULL,
	"tts"    	varchar(25) NULL,
	PRIMARY KEY("tno")
)
GO

INSERT INTO "book"("bno", "bname", "bleader", "bgrade", "bstatus", "bstarttime", "bupdatetime", "bendtime", "bts")
  VALUES('1001', 'book', 'zxy', 1, '1', NULL, NULL, NULL, NULL)
GO
INSERT INTO "book"("bno", "bname", "bleader", "bgrade", "bstatus", "bstarttime", "bupdatetime", "bendtime", "bts")
  VALUES('1002', 'book', 'zxy', 1, '2', NULL, NULL, NULL, NULL)
GO
INSERT INTO "book"("bno", "bname", "bleader", "bgrade", "bstatus", "bstarttime", "bupdatetime", "bendtime", "bts")
  VALUES('1003', 'book2', 'zxy', 1, '2', NULL, NULL, NULL, NULL)
GO
INSERT INTO "bt"("bno", "tno", "btno")
  VALUES('1001', '1001', 1)
GO
INSERT INTO "bt"("bno", "tno", "btno")
  VALUES('1002', '1001', 2)
GO
INSERT INTO "bt"("bno", "tno", "btno")
  VALUES('1003', '1001', 4)
GO
INSERT INTO "essay"("eno", "ename", "eleader", "egrade", "estatus", "estarttime", "eupdatetime", "eendtime", "ets")
  VALUES('1001', '论文', 'zxy', '1', '2', '', NULL, NULL, NULL)
GO
INSERT INTO "essay"("eno", "ename", "eleader", "egrade", "estatus", "estarttime", "eupdatetime", "eendtime", "ets")
  VALUES('1002', '论文2', 'zxy2', '2', '1', NULL, NULL, NULL, NULL)
GO
INSERT INTO "essay"("eno", "ename", "eleader", "egrade", "estatus", "estarttime", "eupdatetime", "eendtime", "ets")
  VALUES('1003', '嘻嘻', 'zxy', '1', '2', NULL, NULL, NULL, NULL)
GO
INSERT INTO "essay"("eno", "ename", "eleader", "egrade", "estatus", "estarttime", "eupdatetime", "eendtime", "ets")
  VALUES('1005', '嘻嘻', 'zxy', '1', '2', NULL, NULL, NULL, NULL)
GO
INSERT INTO "et"("eno", "tno", "etno")
  VALUES('1003', '1002', 1)
GO
INSERT INTO "et"("eno", "tno", "etno")
  VALUES('1004', '1002', 2)
GO
INSERT INTO "et"("eno", "tno", "etno")
  VALUES('1005', '1002', 3)
GO
INSERT INTO "manager"("mno", "mname", "mpass", "mtatus", "mts")
  VALUES('1000', '123', '123', NULL, NULL)
GO
INSERT INTO "manager"("mno", "mname", "mpass", "mtatus", "mts")
  VALUES('1001', 'zxy', '1234', NULL, NULL)
GO
INSERT INTO "manager"("mno", "mname", "mpass", "mtatus", "mts")
  VALUES('1002', '123', '123', NULL, NULL)
GO
INSERT INTO "project"("pno", "pname", "pleader", "pgrade", "pstatus", "pstarttime", "pupdatetime", "pendtime", "pts")
  VALUES('1001', '1001', 'zxy', 1, '2', NULL, NULL, NULL, NULL)
GO
INSERT INTO "project"("pno", "pname", "pleader", "pgrade", "pstatus", "pstarttime", "pupdatetime", "pendtime", "pts")
  VALUES('1002', '1001', 'zxy', 1, NULL, NULL, NULL, NULL, NULL)
GO
INSERT INTO "project"("pno", "pname", "pleader", "pgrade", "pstatus", "pstarttime", "pupdatetime", "pendtime", "pts")
  VALUES('1003', '1001', 'zxy', 1, NULL, NULL, NULL, NULL, NULL)
GO
INSERT INTO "pt"("pno", "tno", "ptno")
  VALUES('1001', '1001', 1007)
GO
INSERT INTO "pt"("pno", "tno", "ptno")
  VALUES('1002', '1002', 1008)
GO
INSERT INTO "pt"("pno", "tno", "ptno")
  VALUES('1003', '1002', 1009)
GO
INSERT INTO "teacher"("tno", "tname", "tsex", "ttel", "tdept", "tduty", "tpass", "temail", "tstatus", "tts")
  VALUES('1001', 'zxy', 1, '123', 'HR', '实习生', 'zxy', '123@qq.com', '1', NULL)
GO
INSERT INTO "teacher"("tno", "tname", "tsex", "ttel", "tdept", "tduty", "tpass", "temail", "tstatus", "tts")
  VALUES('1002', 'zxy2', 1, '123', 'HR', '实习生', 'zxy', '123@qq.com', NULL, NULL)
GO
INSERT INTO "teacher"("tno", "tname", "tsex", "ttel", "tdept", "tduty", "tpass", "temail", "tstatus", "tts")
  VALUES('1005', 'zxy3', 1, '123', 'HR', '实习生', 'zxy', '123@qq.com', NULL, NULL)
GO
INSERT INTO "teacher"("tno", "tname", "tsex", "ttel", "tdept", "tduty", "tpass", "temail", "tstatus", "tts")
  VALUES('1007', 'zxy3', 1, '123', 'HR', '实习生', 'zxy', '123@qq.com', NULL, NULL)
GO
INSERT INTO "teacher"("tno", "tname", "tsex", "ttel", "tdept", "tduty", "tpass", "temail", "tstatus", "tts")
  VALUES('1009', 'zxy1', 1, '123', 'HR', '实习生', 'zxy1', '123@qq.com', NULL, NULL)
GO
